### ISSUE TITLE
Compile overlay

### ISSUE THREAD

**Issue by BaamAlex** [HookedBehemoth/studious-pancake#12]
In your screenshot is an overlay visible. How do I compile this? Or from where do I get it?

**Comment by HookedBehemoth** [comment]
You type `make` after having the dkp switch-dev toolchain installed. If only the overlay wasn't built you might have not cloned the git submodules. Retroactively check those out with `git submodule update --init`.

Precompiled binaries are in the release zip under `/switch/.overlays/studious-pancake.ovl`
