### ISSUE TITLE
Studious-pancake for Mariko?

### ISSUE THREAD

**Issue by TTghostsemir** [HookedBehemoth/studious-pancake#3]
Can you please add Studious-pancake to Mariko?

**Comment by HookedBehemoth** [comment]
Can you test the master branch?

**Comment by TTghostsemir** [comment]
First of all thank you ❤️
It does not want to restart 😭

https://user-images.githubusercontent.com/102698694/214022714-ce107a91-4ee3-4271-8a90-1939264b9fb6.MOV

**Comment by TTghostsemir** [comment]
The same with the nro 😭

https://user-images.githubusercontent.com/102698694/214023527-7b6c733e-7a00-4cda-9f78-d7ffaf3ee5fa.MOV

**Comment by TTghostsemir** [comment]
It restarts now, but the entry is not started

https://user-images.githubusercontent.com/102698694/214163679-dfd5d6c2-8ebc-4c5b-845c-b8dec3155d49.MOV

**Comment by TTghostsemir** [comment]
What is the current status?
Will work continue on it or will it remain as it is now?

**Comment by HookedBehemoth** [comment]
The work was done under the assumption that the OS doesn't reset the RTC registers.
Sadly that is the case. I won't work on this for now as it would require too much effort and I don't even use a Mariko.

**Comment by AciDCooL** [comment]
Can you merge https://github.com/btc08gh/studious-pancake to make it compatible ? Or will it break existing reboot?

**Comment by HookedBehemoth** [comment]
I wrote these patches.
THEY DON'T WORK

Was this shared on GBATemp again?

**Comment by AciDCooL** [comment]
> 

Ah sorry I didn't know, was chatting on discord with someone about it and referenced that repo. Thanks for telling me, was in the process of installing vscode and compiling it myself. Saves me an evening and the misses wouldn't mind, hehe

**Comment by HookedBehemoth** [comment]
Made a release for this now
https://github.com/HookedBehemoth/studious-pancake/releases
You have to update Atmosphère to at least 1.6.0
