### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by impeeza** [HookedBehemoth/studious-pancake#5]
Hi, first at all, thanks a lot for your great work.

I am trying to build latest commit using MSYS under Windows 11, I have a full working DevKitPro environment inside the MSYS, and lots of other homebrew work fine.

The latest commit start to generate some errors recently, I think what on March all build OK.

On MSYS (mingw64) I get these errors:

![image](https://github.com/HookedBehemoth/studious-pancake/assets/41979604/3a2f7346-2075-47b2-93b4-d755189fa9ff)

```
Impeeza@Titan MINGW64 ~/studious-pancake
# make all
make -f Makefile.applet
make[1]: Entering directory '/home/Impeeza/studious-pancake'
payload.cpp
In file included from C:/msys64/home/Impeeza/studious-pancake/common/payload.cpp:16:
C:/msys64/home/Impeeza/studious-pancake/common/payload.hpp:73:27: error: 'uint32_t' in namespace 'std' does not name a type; did you mean 'wint_t'?
   73 |     constexpr inline std::uint32_t const Magic           = 0x43544349; /* ICTC */
      |                           ^~~~~~~~
      |                           wint_t
C:/msys64/home/Impeeza/studious-pancake/common/payload.cpp: In function 'bool Payload::{anonymous}::LoadPayload(const char*, bool)':
C:/msys64/home/Impeeza/studious-pancake/common/payload.cpp:107:89: error: 'Magic' is not a member of 'Payload'
  107 |             if (hekate && *(u32 *)(g_reboot_payload + Payload::MagicOffset) != Payload::Magic)
      |                                                                                         ^~~~~
make[2]: *** [/opt/devkitpro/devkitA64/base_rules:16: payload.o] Error 1
make[1]: *** [Makefile.applet:169: build.nro] Error 2
make[1]: Leaving directory '/home/Impeeza/studious-pancake'
make: *** [Makefile:4: applet] Error 2

Impeeza@Titan MINGW64 ~/studious-pancake
#
```

I have a Ubuntu virtual machine (Ubuntu 22.10), which hasn't been updated long time ago, and have devkitA64 r21-3 installed, the build process works perfectly even if I update manually LibNX to latest commit, but once I update devkitA64 to devkitA64-r22-5 version the build process fail with the same error which on Windows MSYS environment.

Something changed on the libraries of devkitA64 which makes the Studious-pancake code unable to compile.

Again thanks a lot for your help.

**Comment by DacoTaco** [comment]
this is a programming mistake that was not noticed before because of GCC implicitly including a few stdc++ headers with every source, but with GCC 13 they have removed these because source should define what they use, not the compiler (for more info : https://gcc.gnu.org/gcc-13/porting_to.html )

basically, adding cstdint as an include should fix the issue.
(5min googling : https://stackoverflow.com/a/11069163/14661514 )

**Comment by impeeza** [comment]
yeah, you hit the nail,  putting `#include <cstdint>` on the `/studious-pancake/common/payload.hpp` file allow to build with latest libraries.
going to create a PR.

I have find the problem but wasn't sure which file to modify and which library to add, but with your help, found the needed one.

Thanks a lot.
