### ISSUE TITLE
How do you compile it?

### ISSUE THREAD

**Issue by HeikesFootSlave** [HookedBehemoth/studious-pancake#9]
Just curious about how to do it!

If I clone it the = url git@github gives me a permission denied bla bla something with publickey and that I don't have access!

If I compile like that it can't find the tesla.hpp (no file or directory)

If I clone the libtesla repo into the "libs" folder (studious-pancake/libs/) I always get error and it doesn't compile the "ovl" for me!

The "nro" is created just fine!

What am I missing?

**Comment by HookedBehemoth** [comment]
It assumes you have ssh setup I guess...
You can change "git@github.com:" to "https://github.com/"
Make a PR if you are at it

**Comment by TTghostsemir** [comment]
For the overlay you need to rename the lib to tesla and not libtesla

**Comment by HookedBehemoth** [comment]
did it myself https://github.com/HookedBehemoth/studious-pancake/commit/cc9c9ab8da3d8ed927b3fed17328653a3912367a
